/**
 * Plan → G-code 转译层（任务 2.2，方案 B 核心）。
 *
 * 主机保留完整 Plan（预览着色/统计/回溯算法全部依赖它），本模块只是
 * 执行后端：逐动作转译为标准 G-code 行流，速度曲线交给 GRBL 控制器的
 * planner 重新规划。
 *
 * 转译规则（GRBL_PORT_PLAN.md 7.1）：
 * - XYMotion 落笔绘制段 → `G1 X.. Y.. F..`（vFinal × 60 → mm/min）
 * - XYMotion 抬笔空程/首尾行程 → `G0 X.. Y..`（设备 $110/$111 最大速率）
 * - PenMotion → `G1 Z{z} F{zFeed}`（Z 高度经 zaxis 后端映射，任务 2.3）
 * - 头部约定 `G21`（毫米）/ `G90`（绝对）/ `G54`（工作坐标系）；不支持
 *   G91 相对模式，导入解析器负责把外部 G-code 归一化为绝对坐标。
 *
 * 主机 Block 的 vInitial/accel 仅用于 G1 的 F 建议值与主机预计时长估算；
 * 实际速度曲线由设备 $110–$122 决定，两者存在语义偏差（方案 B 既定取舍，
 * 见 GRBL_PORT_PLAN.md 7.4 风险清单）。
 *
 * 动作索引 ↔ G-code 行号双向映射（motionLineRanges / lineToMotion）是
 * 后续进度跟踪与回溯重放（阶段三 3.2/3.3）的根基：头部/脚注行不归属任何
 * 动作（映射 -1）；未产生任何行的动作（如全零长块）映射为 null。
 */
import { type Motion, type Plan, PenMotion, XYMotion } from "./planning.js";
import { penMotionDurationSec, penPctToZMm, type ZAxisConfig } from "./zaxis.js";

/** 零长块阈值（mm）：低于此距离的块不产生 G-code 行 */
const MIN_SEGMENT_MM = 1e-9;

/** 设备限速（$110–$112，mm/min），用于 F 值钳制与主机时长估算；缺省项不钳制 */
export interface GCodeLimits {
  maxVelMmMin?: { x?: number; y?: number; z?: number };
}

export interface TranslateOptions {
  /** Z 轴抬笔后端配置（任务 2.3） */
  z: ZAxisConfig;
  /** 设备限速；缺省时 F 取 Block.vFinal×60、时长按该速度估算 */
  limits?: GCodeLimits;
}

/** 单动作转译上下文：跨动作维护的笔状态（落笔 = true） */
export interface MotionContext {
  z: ZAxisConfig;
  limits?: GCodeLimits;
  /** 进入该动作前笔是否落纸；PenMotion 会更新它 */
  penDown: boolean;
}

export interface GCodeTranslation {
  /** G-code 行数组（不含行尾换行符） */
  lines: string[];
  /** 动作索引 → 行区间 [start, end)，0-based 半开区间；未产生行为 null */
  motionLineRanges: ({ start: number; end: number } | null)[];
  /** 行号 → 动作索引；头部/脚注行 = -1 */
  lineToMotion: number[];
  /**
   * 主机预计总时长（秒）：落笔段按 Block 平均速度受 $110/$111 钳制估算、
   * G0 按 $110/$111 最大速率、PenMotion 按 |ΔZ| ÷ $112 钳制后的 Z 进给。
   * GRBL planner 含梯形加减速与拐角容差，此值必然偏乐观（方案 B 取舍）。
   */
  estimatedDurationSec: number;
}

/** 数值格式化：3 位小数，去尾零（GRBL 均接受；缩短行节省 RX 缓冲窗口） */
export function fmtNumber(n: number): string {
  const value = Object.is(n, -0) ? 0 : n;
  const s = value.toFixed(3);
  return s.includes(".") ? s.replace(/0+$/, "").replace(/\.$/, "") : s;
}

/**
 * 转译单个动作为 G-code 行。笔状态（ctx.penDown）跨动作维护：
 * PenMotion 按笔高 pct 方向更新（pct 升 = 落笔），并据此决定后续
 * XYMotion 是绘制（G1）还是空程（G0）。
 */
export function translateMotion(motion: Motion, ctx: MotionContext): { lines: string[]; estimatedDurationSec: number } {
  const { z, limits, penDown } = ctx;
  const lines: string[] = [];
  let estimatedDurationSec = 0;

  if (motion instanceof PenMotion) {
    // PenMotion 位置即 penPct（0 = 完全抬笔，100 = 完全落笔），直接映射 Z；
    // 笔态方向以 pct 比较（pct 升 = 落笔）。
    const zTarget = penPctToZMm(motion.finalPos, z);
    lines.push(`G1 Z${fmtNumber(zTarget)} F${fmtNumber(z.zFeedMmMin)}`);
    estimatedDurationSec += penMotionDurationSec(motion, z, limits?.maxVelMmMin?.z);
    ctx.penDown = motion.finalPos > motion.initialPos;
    return { lines, estimatedDurationSec };
  }
  if (!(motion instanceof XYMotion)) {
    throw new Error(`Unknown motion type: ${motion.constructor.name}`);
  }

  const xyLimitMmS = xyLimitVelocityMmS(limits);
  for (const block of motion.blocks) {
    if (block.distance < MIN_SEGMENT_MM) continue;
    if (penDown) {
      // 落笔绘制段：F 取块末端速度 ×60（mm/s → mm/min），受 $110/$111 钳制；
      // F ≈ 0（路径终点停顿）时省略 F 字，GRBL 沿用模态进给
      const fMmMin = Math.min(block.vFinal * 60, xyLimitMmMin(limits));
      const f = fMmMin > 0 ? ` F${fmtNumber(fMmMin)}` : "";
      lines.push(`G1 X${fmtNumber(block.p2.x)} Y${fmtNumber(block.p2.y)}${f}`);
      estimatedDurationSec += blockDurationSec(block, xyLimitMmS, false);
    } else {
      // 抬笔空程：G0 由设备按 $110/$111 最大速率执行
      lines.push(`G0 X${fmtNumber(block.p2.x)} Y${fmtNumber(block.p2.y)}`);
      estimatedDurationSec += blockDurationSec(block, xyLimitMmS, true);
    }
  }
  return { lines, estimatedDurationSec };
}

/**
 * 转译整个 Plan 为 G-code。序列开始时视为抬笔（首段行程为 G0 空程）。
 */
export function translatePlanToGCode(plan: Plan, options: TranslateOptions): GCodeTranslation {
  const lines: string[] = [];
  const lineToMotion: number[] = [];
  let estimatedDurationSec = 0;

  const pushLine = (line: string, motionIndex: number) => {
    lines.push(line);
    lineToMotion.push(motionIndex);
  };

  // 头部：坐标模式约定（文档化，不做 G91 相对模式）
  pushLine("; Generated by Bit2AtomPlotGRBL", -1);
  pushLine("; G21 mm / G90 absolute / G54 work coordinate system", -1);
  pushLine("G21", -1);
  pushLine("G90", -1);
  pushLine("G54", -1);

  const motionLineRanges: ({ start: number; end: number } | null)[] = [];
  const ctx: MotionContext = { z: options.z, limits: options.limits, penDown: false };

  plan.motions.forEach((motion, motionIndex) => {
    const startLine = lines.length;
    const r = translateMotion(motion, ctx);
    for (const line of r.lines) pushLine(line, motionIndex);
    estimatedDurationSec += r.estimatedDurationSec;
    motionLineRanges.push(lines.length > startLine ? { start: startLine, end: lines.length } : null);
  });

  // 脚注：Plan 以落笔状态收尾时强制抬笔，防止转译产物直接驱动设备划伤纸面
  if (ctx.penDown) {
    pushLine(`G1 Z${fmtNumber(options.z.zPenUpMm)} F${fmtNumber(options.z.zFeedMmMin)}`, -1);
  }

  return { lines, motionLineRanges, lineToMotion, estimatedDurationSec };
}

/**
 * 单动作时长估算（秒），口径与 translatePlanToGCode 的 estimatedDurationSec
 * 一致。落笔/空程语义未知时按落笔绘制段（G1 匀速近似）处理——G0 实际更快，
 * 估算偏保守，适合用作超时上限。
 */
export function estimateMotionDurationSec(motion: Motion, options: TranslateOptions): number {
  if (motion instanceof PenMotion) {
    return penMotionDurationSec(motion, options.z, options.limits?.maxVelMmMin?.z);
  }
  if (!(motion instanceof XYMotion)) return 0;
  const xyLimitMmS = xyLimitVelocityMmS(options.limits);
  let total = 0;
  for (const block of motion.blocks) {
    total += blockDurationSec(block, xyLimitMmS, false);
  }
  return total;
}

/** XY 合成限速（mm/s）：$110/$111 提供项取最小值；缺省或 ≤0（脏数据，
 * 正常 UI 录入会把 0/负值归一为 undefined）视为未配置，返回 Infinity */
function xyLimitVelocityMmS(limits?: GCodeLimits): number {
  const v = limits?.maxVelMmMin;
  const candidates = [v?.x, v?.y].filter((n): n is number => n != null && n > 0);
  return candidates.length > 0 ? Math.min(...candidates) / 60 : Infinity;
}

function xyLimitMmMin(limits?: GCodeLimits): number {
  const v = xyLimitVelocityMmS(limits);
  return v === Infinity ? Infinity : v * 60;
}

/**
 * 块时长估算（秒）：平均速度 ÷ 限速钳制后按匀速近似。
 * 与 EBB 版 estimateMotionDurationSec 同思路（不建模梯形加减速）；
 * G0 块无主机速度语义，按设备最大速率（缺省回退块平均速度）。
 */
function blockDurationSec(
  block: { distance: number; vInitial: number; vFinal: number },
  xyLimitMmS: number,
  isG0: boolean,
): number {
  if (block.distance <= 0) return 0;
  const avg = (block.vInitial + block.vFinal) / 2;
  const speed = isG0 && xyLimitMmS !== Infinity ? xyLimitMmS : avg;
  const effective = Math.min(speed, xyLimitMmS);
  return effective > 0 ? block.distance / effective : 0;
}
